swagger: "2.0"
#host: muctool.loxal.net
basePath: /
schemes:
 - https
info:
  description: Web Toolkit
  version: 1.0.0
  title: MUCtool API
  contact:
    email: alexander.orlov@loxal.net
  license:
    name: AGPL 3.0
    url: https://www.gnu.org/licenses/agpl-3.0.en.html
tags:
- name: admin
  description: Administrative calls
- name: public
  description: Regular calls

paths:
  /whois:
    get:
      tags:
      - public
      summary: Whois information
      operationId: lookup
      description: |
        Fetches Whois information regarding an IP address
      produces:
      - application/json
      parameters:
      - in: query
        name: queryIP
        description: IPv4/IPv6 to lookup; uses requester's IP address, if not specified
        required: false
        type: string
        format: string
        default: 185.17.205.98
      - in: query
        name: clientId
        description: Client ID
        required: true
        type: string
        format: uuid
        default: f5c88067-88f8-4a5b-b43e-bf0e10a8b857
      responses:
        200:
          description: whois info
          schema:
            type: object
            $ref: '#/definitions/Whois'
        404:
          description: IPv4/IPv6 address not found
        400:
          description: invalid IPv4/IPv6 address or missing query parameter

definitions:
  Whois:
    type: object
    required:
    - ip
    - city
    - cityGeonameId
    - country
    - countryGeonameId
    - countryIso
    - longitude
    - latitude
    - timeZone
    - postalCode
    - isp
    - ispId
    - fraud
    - isTor
    properties:
      ip:
        type: string
        format: ip
        example: 88.217.181.79
      isp:
        type: string
        example: M-net Telekommunikations GmbH
      city:
        type: string
        format: string
        example: Munich
      country:
        type: string
        format: string
        example: Germany
      isTor:
        type: boolean
        description: if `true`, belongs a machine within the Tor Anonymity network
      fraud:
        type: number
        format: float
        description: The probability of the IP used for a fradulent purpose
        example: 0.123
